version: '2'

services:
  docker-runner:
    image:  gitlab/gitlab-runner:${VERSION}
    container_name: gitlab-runner
    restart: always
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL
    privileged: true
