version: '3'

services:
    db:
        restart: always
        image: mariadb:${VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}
        volumes:
            - data:/var/lib/mysql
        ports:
            - 0.0.0.0:3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD

volumes:
    data:
        driver: local
